import React from 'react'
import './globals.css'
import './mdx.css'
import type { Metadata } from 'next'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='flex min-h-screen p-4'>

      <head>

        <link href="https://api.fontshare.com/v2/css?f[]=switzer@300&f[]=gambarino@400&display=swap" rel="stylesheet" />
      </head>

      <body className="flex flex-col gap-8 w-full bg-background text-text font-switzer">
        <Header />
        <main className="w-full flex-1 flex max-w-screen-2xl m-auto ">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
