import React from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='flex h-screen py-4'>
      <body className="flex flex-col w-full">
      <Header />
      <main className="w-full flex-1 flex max-w-screen-2xl m-auto">
        {children}
      </main>
      <Footer />
      </body>
    </html>
  )
}
