export const footerMainLink = 'https://github.com/fescherer'
export const footerLinkedinLink = ''
export const footerFigmaLink = ''
export const footerGithubLink = ''
export const footerYoutubeLink = ''
export const footerTiktokLink = ''
export const footerTwitter = ''
